{% set name = "tippecanoe" %}
{% set version = "2.33.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/felt//{{ name }}/archive/{{ version }}.tar.gz
  sha256: 67f8b3153e22ea9940cc0251fca34e345d9eedca6fdc7f858102e407c0fa09c0

build:
  skip: true  # [win]
  number: 0
  script:
    - ls
    - make -j$CPU_COUNT
    - make install

requirements:
  build:
    - make
    - {{ compiler ('c') }}
    - {{ compiler ('cxx') }}
  host:
    - sqlite
    - zlib

test:
  commands:
    - which tippecanoe
    - tippecanoe --help

about:
  home: https://github.com/felt/tippecanoe
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: Build vector tilesets from large collections of GeoJSON features.

extra:
  recipe-maintainers:
    - mxr-conda
    - rluria14
    - oblute
    - dbrnz
