{% set name = "tippecanoe" %}
{% set version = "2.32.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/felt//{{ name }}/archive/{{ version }}.tar.gz
  sha256: 3c1936108e372d218c5b7e4acd4b279d8fd6f5ab0a60be033ef8a06ea03af2fe

build:
  skip: true  # [win]
  number: 0
  script:
    - ls
    - make -j$CPU_COUNT
    - make install

requirements:
  build:
    - make
    - {{ compiler ('c') }}
    - {{ compiler ('cxx') }}
  host:
    - sqlite
    - zlib

test:
  commands:
    - which tippecanoe
    - tippecanoe --help

about:
  home: https://github.com/felt/tippecanoe
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: Build vector tilesets from large collections of GeoJSON features.

extra:
  recipe-maintainers:
    - mxr-conda
    - rluria14
    - oblute
    - dbrnz
