schema_version: 1

context:
  name: tippecanoe
  version: "2.79.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/felt//${{ name }}/archive/${{ version }}.tar.gz
  sha256: b0fd9df49b6efc988288ea48774822c6de19eb48428017f27ee0b3b01d44f05d

build:
  number: 0
  skip: win
  script:
    - ls
    - make -j$CPU_COUNT
    - make install

requirements:
  build:
    - make
    - ${{ compiler ('c') }}
    - ${{ compiler ('cxx') }}
    - ${{ stdlib("c") }}
  host:
    - sqlite
    - zlib

tests:
  - script:
      - which tippecanoe
      - tippecanoe --help

about:
  license: BSD-2-Clause
  license_file: LICENSE.md
  summary: Build vector tilesets from large collections of GeoJSON features.
  homepage: https://github.com/felt/tippecanoe

extra:
  recipe-maintainers:
    - mxr-conda
    - rluria14
    - oblute
    - dbrnz
    - hobu
